#!/bin/bash

: '

Variables and Arrays

variable and array: Variable and arrays are nothing but its a container for storing values at run time. Its a memory location pointer.

Array is also a variable which stores list of values and can be accessed using index position.

e.g.
variable_name=<value>
Note: There should not be space between variable name and assignment operator and value
Variable rules: 
1.	Variable name can be started with any char from a-z|A-Z|_
2. 	Variable name must not contain any special char except _ (underscore)
3.	Variable name can contain the numeric digit.
4. 	Variable name must not start with numeric digit.
5.	Variable name must not contain spaces between 2 words.

Following are the valid variable names:
my_name="ABC"
yourName="XYZ"
name1="test"
name_2="test2"
_specialname="special value"

Following are the invalid variable names:
1Name="ABC"
your name="XYZ"
@email="abc@mail.com"

'
#For e.g.

Name='Zee Entertainment ltd.'
company_group='Cinema Ltd.'
array_1=(Apple Banana Orange Custer Melon)

# Accessing Variable and Arrays
echo "Print Variable Name"
echo "${Name}"
echo
echo "Print variable company_group:"
echo "${company_group}"
echo
echo "Printing All values of Array:"
echo "${array_1[@]}"
echo
echo "Accessing Array by its index position"
echo "${array_1[1]}"
echo "Alternate way Print first element"
echo "${array_1:0}"
echo "Print second element starting from second char"
echo "${array_1:1}"
echo
echo "Print all the element of array"
echo "${array_1[@]:0}"
echo
echo "Print length of selected array element"
echo "${#array_1[1]}"
echo
echo "Print all the array elements from starting index position 1"
echo "${array_1[@]:1}"
echo
echo "Print all the array elements from range Index 1 to 3"
echo "${array_1[@]:1:3}"
echo
echo "Print length of Array"
echo "${#array_1[@]}"
echo
echo "Replace the substring with given string e.g. replace pp from apple to tt and print"
echo "${array_1[@]//pp/tt}"
echo
echo "Replace element from banana to tomato"
echo "${array_1[1]//Banana/tomato}"
echo

